"""
Pydantic schemas for the Audit Log module
"""

from datetime import datetime
from typing import Any
from uuid import UUID

from app.models.audit import AuditAction

from .base_schema import BaseSchema


class AuditLogResponse(BaseSchema):
    """Schema for returning immutable audit trail records generated by PostgreSQL triggers"""

    id: UUID
    table_name: str
    action_type: AuditAction
    record_id: UUID

    old_data: dict[str, Any] | None = None
    new_data: dict[str, Any] | None = None

    changed_by: UUID | None = None
    changed_at: datetime
