"""make_doctor_id_nullable_for_walkin

Revision ID: 73e24f19d0c8
Revises: abb14583fcfb
Create Date: 2026-06-28 18:25:09.121849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e24f19d0c8'
down_revision: Union[str, Sequence[str], None] = 'abb14583fcfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'doctor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
