"""add is_active to patient

Revision ID: abb14583fcfb
Revises: cc7f72375c93
Create Date: 2026-06-08 01:33:25.330875

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abb14583fcfb"
down_revision: str | Sequence[str] | None = "cc7f72375c93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patient", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patient", "is_active")
    # ### end Alembic commands ###
