"""test models app

Revision ID: cc7f72375c93
Revises:
Create Date: 2026-05-25 20:20:25.473875

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc7f72375c93"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("allergy_name_key"), "allergy", type_="unique")
    op.create_unique_constraint(op.f("uq_allergy_name"), "allergy", ["name"])
    op.alter_column(
        "appointment",
        "status",
        existing_type=postgresql.ENUM(
            "SCHEDULED",
            "WAITING",
            "READY",
            "COMPLETED",
            "CANCELED",
            name="appointment_status",
        ),
        nullable=False,
        existing_server_default=sa.text("'SCHEDULED'::appointment_status"),
    )
    op.alter_column(
        "appointment",
        "origin",
        existing_type=postgresql.ENUM("VALSYNC", "VALCARE", name="appointment_origin"),
        nullable=False,
        existing_server_default=sa.text("'VALSYNC'::appointment_origin"),
    )
    op.alter_column(
        "appointment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "appointment",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "audit_log",
        "table_name",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    audit_action_enum = sa.Enum("INSERT", "UPDATE", "DELETE", name="audit_action")

    audit_action_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "audit_log",
        "action_type",
        existing_type=sa.VARCHAR(length=10),
        type_=audit_action_enum,
        existing_nullable=False,
        postgresql_using="action_type::audit_action",
    )
    op.alter_column(
        "audit_log",
        "changed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("chronic_disease_name_key"), "chronic_disease", type_="unique")
    op.create_unique_constraint(op.f("uq_chronic_disease_name"), "chronic_disease", ["name"])
    op.alter_column(
        "consultation",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "consultation",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("consultation_appointment_id_key"), "consultation", type_="unique")
    op.create_unique_constraint(op.f("uq_consultation_appointment_id"), "consultation", ["appointment_id"])
    op.drop_constraint(op.f("diagnosis_catalog_code_key"), "diagnosis_catalog", type_="unique")
    op.create_unique_constraint(op.f("uq_diagnosis_catalog_code"), "diagnosis_catalog", ["code"])
    op.alter_column(
        "doctor_profile",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("doctor_profile_staff_id_key"), "doctor_profile", type_="unique")
    op.create_unique_constraint(op.f("uq_doctor_profile_staff_id"), "doctor_profile", ["staff_id"])
    op.add_column(
        "medical_background",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )

    blood_type_enum = sa.Enum(
        "A_POS",
        "A_NEG",
        "B_POS",
        "B_NEG",
        "AB_POS",
        "AB_NEG",
        "O_POS",
        "O_NEG",
        name="blood_type_enum",
    )

    blood_type_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "medical_background",
        "blood_type",
        existing_type=sa.VARCHAR(length=10),
        type_=blood_type_enum,
        existing_nullable=True,
        postgresql_using="blood_type::blood_type_enum",
    )
    op.alter_column(
        "medical_background",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("medical_background_patient_id_key"), "medical_background", type_="unique")
    op.create_unique_constraint(op.f("uq_medical_background_patient_id"), "medical_background", ["patient_id"])

    gender_enum = sa.Enum("MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY", name="gender_enum")

    gender_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "patient",
        "gender",
        existing_type=sa.VARCHAR(length=20),
        type_=gender_enum,
        existing_nullable=True,
        postgresql_using="gender::gender_enum",
    )
    op.alter_column(
        "patient",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "patient",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("patient_document_number_key"), "patient", type_="unique")
    op.create_unique_constraint(op.f("uq_patient_document_number"), "patient", ["document_number"])
    op.alter_column(
        "patient_account",
        "is_email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "patient_account",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("patient_account_email_key"), "patient_account", type_="unique")
    op.drop_constraint(op.f("patient_account_patient_id_key"), "patient_account", type_="unique")
    op.create_unique_constraint(op.f("uq_patient_account_email"), "patient_account", ["email"])
    op.create_unique_constraint(op.f("uq_patient_account_patient_id"), "patient_account", ["patient_id"])
    op.alter_column(
        "prescription",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "specialty",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("specialty_name_key"), "specialty", type_="unique")
    op.create_unique_constraint(op.f("uq_specialty_name"), "specialty", ["name"])
    op.alter_column(
        "staff",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )
    op.alter_column(
        "staff",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "staff",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("staff_email_key"), "staff", type_="unique")
    op.create_unique_constraint(op.f("uq_staff_email"), "staff", ["email"])
    op.alter_column(
        "triage",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("triage_appointment_id_key"), "triage", type_="unique")
    op.create_unique_constraint(op.f("uq_triage_appointment_id"), "triage", ["appointment_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_triage_appointment_id"), "triage", type_="unique")
    op.create_unique_constraint(
        op.f("triage_appointment_id_key"),
        "triage",
        ["appointment_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "triage",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("uq_staff_email"), "staff", type_="unique")
    op.create_unique_constraint(op.f("staff_email_key"), "staff", ["email"], postgresql_nulls_not_distinct=False)
    op.alter_column(
        "staff",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "staff",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "staff",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )
    op.drop_constraint(op.f("uq_specialty_name"), "specialty", type_="unique")
    op.create_unique_constraint(
        op.f("specialty_name_key"),
        "specialty",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "specialty",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "prescription",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("uq_patient_account_patient_id"), "patient_account", type_="unique")
    op.drop_constraint(op.f("uq_patient_account_email"), "patient_account", type_="unique")
    op.create_unique_constraint(
        op.f("patient_account_patient_id_key"),
        "patient_account",
        ["patient_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("patient_account_email_key"),
        "patient_account",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "patient_account",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "patient_account",
        "is_email_verified",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_constraint(op.f("uq_patient_document_number"), "patient", type_="unique")
    op.create_unique_constraint(
        op.f("patient_document_number_key"),
        "patient",
        ["document_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "patient",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "patient",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    gender_enum = sa.Enum("MALE", "FEMALE", "OTHER", "PREFER_NOT_TO_SAY", name="gender_enum")

    op.alter_column(
        "patient",
        "gender",
        existing_type=gender_enum,
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
        postgresql_using="gender::text",
    )
    gender_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(op.f("uq_medical_background_patient_id"), "medical_background", type_="unique")
    op.create_unique_constraint(
        op.f("medical_background_patient_id_key"),
        "medical_background",
        ["patient_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "medical_background",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    blood_type_enum = sa.Enum(
        "A_POS",
        "A_NEG",
        "B_POS",
        "B_NEG",
        "AB_POS",
        "AB_NEG",
        "O_POS",
        "O_NEG",
        name="blood_type_enum",
    )

    op.alter_column(
        "medical_background",
        "blood_type",
        existing_type=blood_type_enum,
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
        postgresql_using="blood_type::text",
    )
    blood_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column("medical_background", "created_at")
    op.drop_constraint(op.f("uq_doctor_profile_staff_id"), "doctor_profile", type_="unique")
    op.create_unique_constraint(
        op.f("doctor_profile_staff_id_key"),
        "doctor_profile",
        ["staff_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "doctor_profile",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("uq_diagnosis_catalog_code"), "diagnosis_catalog", type_="unique")
    op.create_unique_constraint(
        op.f("diagnosis_catalog_code_key"),
        "diagnosis_catalog",
        ["code"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(op.f("uq_consultation_appointment_id"), "consultation", type_="unique")
    op.create_unique_constraint(
        op.f("consultation_appointment_id_key"),
        "consultation",
        ["appointment_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "consultation",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "consultation",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint(op.f("uq_chronic_disease_name"), "chronic_disease", type_="unique")
    op.create_unique_constraint(
        op.f("chronic_disease_name_key"),
        "chronic_disease",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "audit_log",
        "changed_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )

    audit_action_enum = sa.Enum("INSERT", "UPDATE", "DELETE", name="audit_action")

    op.alter_column(
        "audit_log",
        "action_type",
        existing_type=audit_action_enum,
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
        postgresql_using="action_type::text",
    )
    audit_action_enum.drop(op.get_bind(), checkfirst=True)
    op.alter_column(
        "audit_log",
        "table_name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "appointment",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "appointment",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "appointment",
        "origin",
        existing_type=postgresql.ENUM("VALSYNC", "VALCARE", name="appointment_origin"),
        nullable=True,
        existing_server_default=sa.text("'VALSYNC'::appointment_origin"),
    )
    op.alter_column(
        "appointment",
        "status",
        existing_type=postgresql.ENUM(
            "SCHEDULED",
            "WAITING",
            "READY",
            "COMPLETED",
            "CANCELED",
            name="appointment_status",
        ),
        nullable=True,
        existing_server_default=sa.text("'SCHEDULED'::appointment_status"),
    )
    op.drop_constraint(op.f("uq_allergy_name"), "allergy", type_="unique")
    op.create_unique_constraint(
        op.f("allergy_name_key"),
        "allergy",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
